// Code generated by MockGen. DO NOT EDIT.
// Source: transfer.go

// Package transfer is a generated GoMock package.
package transfer

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEpisodeParser is a mock of EpisodeParser interface.
type MockEpisodeParser struct {
	ctrl     *gomock.Controller
	recorder *MockEpisodeParserMockRecorder
}

// MockEpisodeParserMockRecorder is the mock recorder for MockEpisodeParser.
type MockEpisodeParserMockRecorder struct {
	mock *MockEpisodeParser
}

// NewMockEpisodeParser creates a new mock instance.
func NewMockEpisodeParser(ctrl *gomock.Controller) *MockEpisodeParser {
	mock := &MockEpisodeParser{ctrl: ctrl}
	mock.recorder = &MockEpisodeParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEpisodeParser) EXPECT() *MockEpisodeParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockEpisodeParser) Parse(ctx context.Context, fileName string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", ctx, fileName)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockEpisodeParserMockRecorder) Parse(ctx, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockEpisodeParser)(nil).Parse), ctx, fileName)
}

// MockFileTransfer is a mock of FileTransfer interface.
type MockFileTransfer struct {
	ctrl     *gomock.Controller
	recorder *MockFileTransferMockRecorder
}

// MockFileTransferMockRecorder is the mock recorder for MockFileTransfer.
type MockFileTransferMockRecorder struct {
	mock *MockFileTransfer
}

// NewMockFileTransfer creates a new mock instance.
func NewMockFileTransfer(ctrl *gomock.Controller) *MockFileTransfer {
	mock := &MockFileTransfer{ctrl: ctrl}
	mock.recorder = &MockFileTransferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileTransfer) EXPECT() *MockFileTransferMockRecorder {
	return m.recorder
}

// Transfer mocks base method.
func (m *MockFileTransfer) Transfer(ctx context.Context, src, dst string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, src, dst)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockFileTransferMockRecorder) Transfer(ctx, src, dst interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockFileTransfer)(nil).Transfer), ctx, src, dst)
}

// MockTransferFilesRepo is a mock of TransferFilesRepo interface.
type MockTransferFilesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTransferFilesRepoMockRecorder
}

// MockTransferFilesRepoMockRecorder is the mock recorder for MockTransferFilesRepo.
type MockTransferFilesRepoMockRecorder struct {
	mock *MockTransferFilesRepo
}

// NewMockTransferFilesRepo creates a new mock instance.
func NewMockTransferFilesRepo(ctrl *gomock.Controller) *MockTransferFilesRepo {
	mock := &MockTransferFilesRepo{ctrl: ctrl}
	mock.recorder = &MockTransferFilesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferFilesRepo) EXPECT() *MockTransferFilesRepoMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockTransferFilesRepo) Del(ctx context.Context, req DeleteFileTransferredReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockTransferFilesRepoMockRecorder) Del(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockTransferFilesRepo)(nil).Del), ctx, req)
}

// Get mocks base method.
func (m *MockTransferFilesRepo) Get(ctx context.Context, req GetFileTransferredReq) (FileTransferred, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(FileTransferred)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTransferFilesRepoMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTransferFilesRepo)(nil).Get), ctx, req)
}

// List mocks base method.
func (m *MockTransferFilesRepo) List(ctx context.Context, req ListFileTransferredReq) ([]FileTransferred, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]FileTransferred)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTransferFilesRepoMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTransferFilesRepo)(nil).List), ctx, req)
}

// Set mocks base method.
func (m *MockTransferFilesRepo) Set(ctx context.Context, fileTransferred FileTransferred) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, fileTransferred)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockTransferFilesRepoMockRecorder) Set(ctx, fileTransferred interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockTransferFilesRepo)(nil).Set), ctx, fileTransferred)
}
