// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package magnet is a generated GoMock package.
package magnet

import (
	context "context"
	reflect "reflect"

	downloader "github.com/MangataL/BangumiBuddy/internal/downloader"
	meta "github.com/MangataL/BangumiBuddy/internal/meta"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteTask mocks base method.
func (m *MockRepository) DeleteTask(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockRepositoryMockRecorder) DeleteTask(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockRepository)(nil).DeleteTask), ctx, taskID)
}

// GetTask mocks base method.
func (m *MockRepository) GetTask(ctx context.Context, taskID string) (Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, taskID)
	ret0, _ := ret[0].(Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockRepositoryMockRecorder) GetTask(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockRepository)(nil).GetTask), ctx, taskID)
}

// GetTaskByHash mocks base method.
func (m *MockRepository) GetTaskByHash(ctx context.Context, hash string) (Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByHash", ctx, hash)
	ret0, _ := ret[0].(Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByHash indicates an expected call of GetTaskByHash.
func (mr *MockRepositoryMockRecorder) GetTaskByHash(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByHash", reflect.TypeOf((*MockRepository)(nil).GetTaskByHash), ctx, hash)
}

// ListTasks mocks base method.
func (m *MockRepository) ListTasks(ctx context.Context, req ListTasksReq) ([]Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, req)
	ret0, _ := ret[0].([]Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockRepositoryMockRecorder) ListTasks(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockRepository)(nil).ListTasks), ctx, req)
}

// SaveTask mocks base method.
func (m *MockRepository) SaveTask(ctx context.Context, task Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTask indicates an expected call of SaveTask.
func (mr *MockRepositoryMockRecorder) SaveTask(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTask", reflect.TypeOf((*MockRepository)(nil).SaveTask), ctx, task)
}

// MockMetaParser is a mock of MetaParser interface.
type MockMetaParser struct {
	ctrl     *gomock.Controller
	recorder *MockMetaParserMockRecorder
}

// MockMetaParserMockRecorder is the mock recorder for MockMetaParser.
type MockMetaParserMockRecorder struct {
	mock *MockMetaParser
}

// NewMockMetaParser creates a new mock instance.
func NewMockMetaParser(ctrl *gomock.Controller) *MockMetaParser {
	mock := &MockMetaParser{ctrl: ctrl}
	mock.recorder = &MockMetaParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetaParser) EXPECT() *MockMetaParserMockRecorder {
	return m.recorder
}

// ParseFile mocks base method.
func (m *MockMetaParser) ParseFile(ctx context.Context, fileName string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFile", ctx, fileName)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseFile indicates an expected call of ParseFile.
func (mr *MockMetaParserMockRecorder) ParseFile(ctx, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFile", reflect.TypeOf((*MockMetaParser)(nil).ParseFile), ctx, fileName)
}

// ParseMetaByID mocks base method.
func (m *MockMetaParser) ParseMetaByID(ctx context.Context, tmdbID int, downloadType downloader.DownloadType) (meta.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseMetaByID", ctx, tmdbID, downloadType)
	ret0, _ := ret[0].(meta.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseMetaByID indicates an expected call of ParseMetaByID.
func (mr *MockMetaParserMockRecorder) ParseMetaByID(ctx, tmdbID, downloadType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseMetaByID", reflect.TypeOf((*MockMetaParser)(nil).ParseMetaByID), ctx, tmdbID, downloadType)
}

// ParseMetaByTorrent mocks base method.
func (m *MockMetaParser) ParseMetaByTorrent(ctx context.Context, torrentName string, downloadType downloader.DownloadType) (meta.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseMetaByTorrent", ctx, torrentName, downloadType)
	ret0, _ := ret[0].(meta.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseMetaByTorrent indicates an expected call of ParseMetaByTorrent.
func (mr *MockMetaParserMockRecorder) ParseMetaByTorrent(ctx, torrentName, downloadType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseMetaByTorrent", reflect.TypeOf((*MockMetaParser)(nil).ParseMetaByTorrent), ctx, torrentName, downloadType)
}

// ParseReleaseGroup mocks base method.
func (m *MockMetaParser) ParseReleaseGroup(ctx context.Context, torrentName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseReleaseGroup", ctx, torrentName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseReleaseGroup indicates an expected call of ParseReleaseGroup.
func (mr *MockMetaParserMockRecorder) ParseReleaseGroup(ctx, torrentName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseReleaseGroup", reflect.TypeOf((*MockMetaParser)(nil).ParseReleaseGroup), ctx, torrentName)
}
